### ISSUE TITLE
Updating tutorial instructions with tip on how to install current branch of tobac with ability to switch to another branch? 

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac-tutorials#11]
In the [instructions on how to use the tutorials](https://github.com/climate-processes/tobac-tutorials/blob/master/docs/RunningTutorials.md), maybe it could be useful to indicate how to install `tobac` with the enablement of branch switches. If you follow the instructions, you currently only install the ```v2.0-dev``` branch, since this is the branch compatible with the tutorials. I could imagine that users would like to be able to switch between ```v2.0-dev``` and ```main``` (or a different branch) when testing the `tobac` code for their purposes. This could be simply  achieved by installing the package with: 

`pip install -e .`

This way you have access to the code of the checked out branch, but you can easily access code from the other branches as well by when you change the branch. 

I am just not sure if you need to install the conda requirements for each single branch separately or if there is a way of installing the requirements from all branches at the same time?

**Comment by fsenf** [comment]
@JuliaKukulies : I fear I did not understand your proposal. Assume you have a separate conda env for tracking and you install tobac into this conda env. How can you switch between the two tobac versions e.g. within a python script or a notebook? 

@w-k-jones , @freemansw1: Do you know more?

**Comment by JuliaKukulies** [comment]
@fsenf  Sorry, I was a bit unclear about this. I think it is not possible (and probably not desirable?) to change the version/branch within the notebook. It is a more general advice that is not only specific for the tutorials and maybe more relevant for users who want to contribute or make changes in the code. 

 `pip install -e` will affect the code you import to a notebook when you edit the code in the project folder. This means you can checkout to another branch and access code from this branch (as opposed to the normal installation with which you only install a specific branch, in this case `v2.0-dev` ). It is really just a detail and maybe more relevant for developers, but I think as a user I would wonder if I had to uninstall and reinstall `tobac` each time I want to access the code from e.g. latest release instead of `v2.0-dev`.

**Comment by fsenf** [comment]
OK, thanks for clarification!

**Comment by fsenf** [comment]
OK, solved with #12.
