### ISSUE TITLE
PR template needs some improvement

### ISSUE THREAD

**Issue by fsenf** [tobac-project/tobac-tutorials#15]
Doing a PR just a few minutes ago, it felt that the template could provide more structure to input more descriptive parts and not only check boxes. BTW, quite a lot check boxes ....

**Comment by JuliaKukulies** [comment]
All right, no problem, I am happy to update this! Do you have specific suggestions for which check points we can delete? Nr. 2, 4 and the last three are the ones that seem the least specific so maybe these? Some points may seem redundant; the `README.md` already says to upload example data for example, but I think the check boxes can serve as good reminders of the things that you should have taken care of before submitting a PR. It also can help the reviewer to know what has been already done. Maybe adding a check box that says if changes has already been made to `index.rst`? 


Regarding "more structure to input more descriptive parts", what do you mean exactly? Do you mean to include more detailed descriptions from the `README.md` or more information on the example structure of a new tutorial ?

**Comment by fsenf** [comment]
I actually had the feeling that
- I would love to have more guidance what additional information I would need to provide
- it would be easier if the check boxes are kind of clustered into labelled categories.

I will prepare a draft template in the next minutes ...

**Comment by JuliaKukulies** [comment]
Alright, I am happy with your update! You can close the issue, when merging new template.
