### ISSUE TITLE
module 'tobac' has no attribute 'themes'

### ISSUE THREAD

**Issue by zxdawn** [tobac-project/tobac-tutorials#3]
I checked one notebook named `Example_OLR_Tracking_satellite.ipynb` and got this error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-efcc7effea23> in <module>
      1 # Feature detection and save results to file:
      2 print('starting feature detection')
----> 3 Features=tobac.themes.tobac_v1.feature_detection_multithreshold(OLR,dxy,**parameters_features)
      4 # Features=tobac.feature_detection(OLR,dxy,**parameters_features)
      5 Features.to_hdf(os.path.join(savedir,'Features.h5'),'table')

AttributeError: module 'tobac' has no attribute 'themes'
```

It seems this is still under developing?
This is the info of my tobac:
```
tobac                     1.2                        py_0    conda-forge
```

**Comment by zxdawn** [comment]
Ha, OK. It should be `tobac.feature_detection_multithreshold`.

**Comment by fsenf** [comment]
Good Point! We started to mix `master`and `v2.0-dev` activities in our tutorial repo...

`tobac.themes.tobac_v1` is already referring to the structure of the next planed release.

**Comment by zxdawn** [comment]
Thanks! I'll keep this issue open until the next release.

**Comment by mheikenfeld** [comment]
Sorry for the confusion here. My bad, initially I created the 2.0-dev branch for that exact purpose, but then I realised that the examples are part of the repository in the tobac 1.x branch anyway, so this entire repository mainly aims at 2.x...

So my suggestion would be to remove the 2.0-dev branch and clearly state in the readme file that this repository is for tobac 2.x. What do you think, @fsenf @zxdawn ?

**Comment by fsenf** [comment]
I aggree

**Comment by fsenf** [comment]
agree (that way)

**Comment by zxdawn** [comment]
Agree ;)

**Comment by mheikenfeld** [comment]
I have deleted the v2.0-dev branch and added some information in #4 ...
