### ISSUE TITLE
Where should example data be uploaded?

### ISSUE THREAD

**Issue by fsenf** [tobac-project/tobac-tutorials#8]
This issue is meant for discussions.

**Comment by fsenf** [comment]
**Current Status:**
* current example are hosted on https://zenodo.org/record/3195910#.YgvtR3VKj0o 
* and come through upload of data to the github project https://github.com/climate-processes/tobac_example_data 
* final release of github project brings them to zenodo.

**Some Discussion Points:**
* a github project is not ideal for uploading (large) data
* access for data upload is rather limited currently
* the user need to have access to his or her own data

**Comment by fsenf** [comment]
**a practical solution**
* when a user provide a tutorial he or she care for data upload 
* this could be done with a separate data upload per tutorial
* we could recommend to
  * use zenodo as data base (if data size < 50 GB)
  * indicate in the title that data are using for tobac tutorials / tobac example or so
  * zenodo allows to group data into "communities" --> makes a bit more work for the one in charge to except data entries to community

**Comment by JuliaKukulies** [comment]
I think that managing the data via a zenodo community sounds actually like a good solution. I understand it as if there is no total size limit per community, just for a single dataset upload. It is  probably practical if anybody is allowed to upload, but that it is managed what officially belongs to the tobac community and what not.

It could be a requirement that data has to be uploaded to zenodo and be accepted by the community (preferrably by the same person who reviews the PR) before the tutorial PR is merged.

**Comment by fsenf** [comment]
Data upload description was included in the contributing section (README.md) via #13
